# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ShieldCli < Formula
  desc "Shield CLI - Secure Tunnel Connector"
  homepage "https://github.com/fengyily/shield-cli"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fengyily/shield-cli/releases/download/v0.1.1/shield-darwin-amd64.tar.gz"
      sha256 "1fac1c213d2350495252448a716e468f0e49486a66c7c24d0ec64868a8d7a722"

      define_method(:install) do
        bin.install "shield"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fengyily/shield-cli/releases/download/v0.1.1/shield-darwin-arm64.tar.gz"
      sha256 "437491ca3faac9f3feb05675681ffe033171fecb72a336789093a3580f10df1e"

      define_method(:install) do
        bin.install "shield"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fengyily/shield-cli/releases/download/v0.1.1/shield-linux-amd64.tar.gz"
      sha256 "f1dc26253bb736a0e39aa9574f73dbca033799cfc68ecc039dfd445b73d41d44"
      define_method(:install) do
        bin.install "shield"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fengyily/shield-cli/releases/download/v0.1.1/shield-linux-arm64.tar.gz"
      sha256 "b6c4fab5ccdcb716d6ddf6d44e020955ed388c241cc5492046653167401e48e6"
      define_method(:install) do
        bin.install "shield"
      end
    end
  end

  def caveats
    <<~EOS
      Usage:
        shield <protocol> [ip:port]

      Examples:
        shield ssh                  # 127.0.0.1:22
        shield ssh 2222             # 127.0.0.1:2222
        shield ssh 10.0.0.2        # 10.0.0.2:22
        shield ssh 10.0.0.2:2222   # 10.0.0.2:2222
        shield http 3000            # 127.0.0.1:3000
        shield rdp 192.168.1.100   # 192.168.1.100:3389

      Supported protocols: ssh, http, https, rdp, vnc, telnet

      Run 'shield --help' for more options.
    EOS
  end

  test do
    system "#{bin}/shield", "--help"
  end
end
