# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ShieldCli < Formula
  desc "Shield CLI - Secure Tunnel Connector"
  homepage "https://github.com/fengyily/shield-cli"
  version "0.3.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fengyily/shield-cli/releases/download/v0.3.5/shield-darwin-amd64.tar.gz"
      sha256 "8ad39ca57dc869f60afb6d3a1a3c336aeea30ff40599fee4c8f11c0b8b7b4894"

      define_method(:install) do
        bin.install "shield"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fengyily/shield-cli/releases/download/v0.3.5/shield-darwin-arm64.tar.gz"
      sha256 "555083b8e622884118f27222fcef048f1bc4fa9105ea0cf3a7a37698fcad113b"

      define_method(:install) do
        bin.install "shield"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fengyily/shield-cli/releases/download/v0.3.5/shield-linux-amd64.tar.gz"
      sha256 "2446ea9105fcc1d827a6af8d0390e15dcb24193cb308ee60f8e68a615f2ce130"
      define_method(:install) do
        bin.install "shield"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fengyily/shield-cli/releases/download/v0.3.5/shield-linux-arm64.tar.gz"
      sha256 "681e91bd905acbd59e8575ff4c51647fe61b965e17650a8049bc37bf6218b2d5"
      define_method(:install) do
        bin.install "shield"
      end
    end
  end

  def caveats
    <<~EOS
      Web UI (recommended):
        shield start                # Open http://localhost:8181

      Command line (for servers):
        shield ssh                  # 127.0.0.1:22
        shield ssh 10.0.0.2        # 10.0.0.2:22
        shield rdp 192.168.1.100   # 192.168.1.100:3389
        shield http 3000            # 127.0.0.1:3000

      Supported protocols: ssh, http, https, rdp, vnc, telnet

      Run 'shield --help' for more options.
    EOS
  end

  test do
    system "#{bin}/shield", "--help"
  end
end
