# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ShieldCli < Formula
  desc "Shield CLI - Secure Tunnel Connector"
  homepage "https://github.com/fengyily/shield-cli"
  version "0.2.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fengyily/shield-cli/releases/download/v0.2.4/shield-darwin-amd64.tar.gz"
      sha256 "ffa6f76977713a8f2d528b93f9cadcb08da424357529557d9f1dc1515fbc8179"

      define_method(:install) do
        bin.install "shield"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fengyily/shield-cli/releases/download/v0.2.4/shield-darwin-arm64.tar.gz"
      sha256 "e0567c49842640138645ee87c97b32b46ae4bcedc2e46bd9bc720c2eccf1735c"

      define_method(:install) do
        bin.install "shield"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fengyily/shield-cli/releases/download/v0.2.4/shield-linux-amd64.tar.gz"
      sha256 "742b05974f9338fe99ad07a8d3c8602e409d585a686b91ef6e9275fc49e257aa"
      define_method(:install) do
        bin.install "shield"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fengyily/shield-cli/releases/download/v0.2.4/shield-linux-arm64.tar.gz"
      sha256 "dc1c3a25518fa44f473d55cc0121bcee46a35b7e8e50cfa8eb22181b4e70c520"
      define_method(:install) do
        bin.install "shield"
      end
    end
  end

  def caveats
    <<~EOS
      Web UI (recommended):
        shield start                # Open http://localhost:8181

      Command line (for servers):
        shield ssh                  # 127.0.0.1:22
        shield ssh 10.0.0.2        # 10.0.0.2:22
        shield rdp 192.168.1.100   # 192.168.1.100:3389
        shield http 3000            # 127.0.0.1:3000

      Supported protocols: ssh, http, https, rdp, vnc, telnet

      Run 'shield --help' for more options.
    EOS
  end

  test do
    system "#{bin}/shield", "--help"
  end
end
